In [2]:
import numpy as np

In [7]:
my_list=[1,2,3,4,5,6]

In [8]:
arr=np.array(my_list)

In [9]:
arr

array([1, 2, 3, 4, 5, 6])

In [11]:
arr.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
arr=np.arange(1,11)

In [17]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [22]:
np.ones(4) + 4

array([5., 5., 5., 5.])

In [25]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
arr=np.arange(1,25,4)

In [29]:
arr

array([ 1,  5,  9, 13, 17, 21])

In [30]:
## LineSpace

In [33]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [34]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
np.random.rand(4)

array([0.9325645 , 0.8632606 , 0.91149644, 0.26298886])

In [36]:
np.random.rand(5,5)

array([[0.86260092, 0.8421025 , 0.54874041, 0.22780609, 0.36159094],
       [0.1393331 , 0.33748906, 0.93988991, 0.46860369, 0.85923984],
       [0.09045138, 0.36584768, 0.7588199 , 0.65861129, 0.6863576 ],
       [0.85560194, 0.73100173, 0.06543898, 0.31001228, 0.14442904],
       [0.25382859, 0.16536712, 0.42309346, 0.07968378, 0.17651007]])

In [37]:
np.random.randn(3)

array([1.55509381, 0.69494451, 0.08263122])

In [38]:
np.random.randn(4,4)

array([[ 1.5985139 , -0.66666119, -1.94518173, -1.21676269],
       [-0.48077516,  0.40617456,  0.06451128,  0.41567527],
       [ 0.4037949 ,  0.70849667,  0.23659541,  1.33928198],
       [-0.79707713,  0.26936434,  0.0103442 , -0.61884494]])

In [42]:
arr=np.random.randint(1,100,15)

In [43]:
arr

array([14, 73, 47, 83, 42, 29, 20, 10, 65, 34,  3, 53, 32, 57, 56])

In [52]:
a=arr.reshape(3,5)

In [45]:
arr.max()

83

In [47]:
arr.min()

3

In [50]:
arr.dtype

dtype('int32')

In [51]:
arr.shape

(15,)

In [53]:
a

array([[14, 73, 47, 83, 42],
       [29, 20, 10, 65, 34],
       [ 3, 53, 32, 57, 56]])

In [54]:
a.shape

(3, 5)

In [55]:
##Numpy Indexing

In [56]:
arr=np.arange(0,11)

In [57]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
arr[8]

8

In [59]:
arr[8:]

array([ 8,  9, 10])

In [60]:
arr[:5]

array([0, 1, 2, 3, 4])

In [61]:
arr[1:5]

array([1, 2, 3, 4])

In [62]:
##Broadcasting of value

In [69]:
arr=np.arange(0,11)

In [70]:
arr_part=arr[:6]

In [72]:
arr_part[:]=99

In [73]:
arr_part

array([99, 99, 99, 99, 99, 99])

In [74]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [75]:
arr_copy=arr.copy()

In [76]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [77]:
arr_copy[:]=100

In [78]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [79]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [80]:
arr_2d=np.arange(5,46,5)

In [81]:
arr_2d

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [84]:
arr_2d=arr_2d.reshape(3,3)

In [85]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [86]:
arr_2d[0][0]

5

In [87]:
arr_2d[0]

array([ 5, 10, 15])

In [88]:
arr_2d[2][1]

40

In [90]:
arr_2d[2,1]

40

In [91]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [92]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [93]:
arr=np.arange(1,11)

In [94]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [95]:
arr>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [96]:
arr[arr>6]

array([ 7,  8,  9, 10])

In [99]:
arr_2d=np.arange(50).reshape(5,10)

In [100]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [101]:
arr_2d[2:4,4:6]

array([[24, 25],
       [34, 35]])

In [102]:
arr=np.arange(1,10)

In [103]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [104]:
arr+arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [105]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [106]:
arr*arr

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [107]:
arr-25

array([-24, -23, -22, -21, -20, -19, -18, -17, -16])

In [108]:
arr+29

array([30, 31, 32, 33, 34, 35, 36, 37, 38])

In [109]:
arr=np.arange(0,11)

In [110]:
arr/arr

C:\Users\amany\AppData\Local\Temp\ipykernel_18504\1862401812.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [111]:
1/arr

C:\Users\amany\AppData\Local\Temp\ipykernel_18504\255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [112]:
arr**3

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

In [113]:
np.sqrt(arr)


array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [114]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [115]:
np.max(arr)

10

In [116]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [117]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153])